### PR TITLE
Use sbt-compat lib

### PR DESCRIPTION
**Pull request by 2m**
So the ad-hoc compatibility wrappers would not clash with other plugins that use sbt-compat.

### CODE REVIEW

**Comment by 2m** [comment]
Relevant sbt-compat change: https://github.com/dwijnand/sbt-compat/pull/1

**Comment by raboof** [comment]
sbt-compat 1.1.0 now should have this change, so this PR could be updated :+1:

**Comment by jrudolph** [comment]
Cool, thanks, I'll have a stab.

**Comment by jrudolph** [comment]
Hmm strange it doesn't seem to compile for sbt 0.13. Did that work @2m?

**Comment by 2m** [comment]
Nope. I only tried 1.0.

**Pull request merged**
