### PR TITLE
Adds InlineConfigurationWithExcludes handling

### LINKED ISSUE #67: sbt 0.13.8 support
sbt 0.13.8-RC1 was just released. dependencyGraph and dependencyTree both do not work with it. Build fails with:

```
[error] (compile:ivyReport) java.lang.IllegalStateException: sbt-dependency-graph plugin currently only supports InlineConfiguration of ivy settings (the default in sbt)
```

### PR DESCRIPTION
**Pull request by eed3si9n**
Fixes #67

### CODE REVIEW

**Comment by jrudolph** [comment]
Thanks, @eed3si9n. I'll try to make a release ASAP.

**Comment by hseeberger** [comment]
@jrudolph, looking forward for a new release ;-)

**Comment by hochgi** [comment]
+1

**Comment by metasim** [comment]
+1

**Comment by dcsobral** [comment]
+1

**Comment by jrudolph** [comment]
Released with version 0.7.5.

**Comment by metasim** [comment]
Thanks so much!!

**Pull request merged**
